# Generated by Django 4.1.3 on 2022-12-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
